# DIRS
TEST_DIR := test_dir 
BUILD_DIR := install_dir
DIST_DIR := dist_dir
BUILD_DIR := build

# TETRIS
TETRIS_TEST_DIR := ${TEST_DIR}/tetris
TETRIS_BUILD_DIR := ${BUILD_DIR}/tetris
TETRIS_LIB_DIR := $(TETRIS_BUILD_DIR)

# OBJS
TETRIS_BUILD_FILES_DIR := $(TETRIS_BUILD_DIR)/tetris

# SNAKE
SNAKE_TEST_DIR := ${TEST_DIR}/snake
SNAKE_BUILD_DIR := ${BUILD_DIR}/snake
SNAKE_LIB_DIR := $(SNAKE_BUILD_DIR)

# OBJS
SNAKE_CLI_BUILD_FILES_DIR := $(SNAKE_BUILD_DIR)/snake/snake_cli
SNAKE_DESKTOP_BUILD_FILES_DIR := $(SNAKE_BUILD_DIR)/snake/snake_desktop

# CLI
CLI_BUILD_FILES_DIR := ${BUILD_DIR}/cli

# DESKTOP
DESKTOP_BUILD_FILES_DIR := ${BUILD_DIR}/desktop
