# 1 правило моих проектов → помечать концы названий пользовательских директорий приставкой _dir 
# 2 перед изменением Мейкфайла запушить изменения в Гитлаб

include make/cmake_format.mk
include make/clang.mk
include make/format_clean.mk

include make/compilers.mk
include make/srcs/tetris.mk
include make/srcs/snake.mk

include make/exe_files.mk

include make/all.mk

include make/uninstall.mk

include make/libs.mk

include make/compilation.mk

include make/dvi.mk

include make/dist.mk

include make/play.mk

include make/tests.mk

include make/gcov.mk

include make/clean.mk

include make/cppcheck.mk

include make/gdb.mk
